pipeline {
	agent any
	stages {
		stage('Build Application') {
			steps {
				sh '/usr/local/apache-maven/bin/mvn -f clean package java-tomcat-sample/pom.xml'	
			}
			
			post {
				success {
					echo "Now , Perform Artifact"
					archiveArtifacts artifacts: '**/*.war'	
					}
			}
		}
		

	}
}
