pipeline {
	agent any
	stages {
		stage('Build Application') {
			steps {
				sh '/usr/local/apache-maven/bin/mvn -f java-tomcat-sample/pom.xml clean package'	
			}
			
			post {
				success {
					echo "Now , Perform Artifact"
					archiveArtifacts artifacts: '**/*.war'	
					}
			}
		}
		
		stage('Deploy Application to Staging Environment') {
			steps {
				build job : 'Deploy_Application_Staging_Env'	
			}
			
		}
		stage('Deploy Application to Prod Environment') {
			steps {
				timeout(time:5, unit:'DAYS'){
                    		input message:'Approve PRODUCTION Deployment?'
                		}
				build job : 'Deploy_Application_Prod_Env'	
			}
			
		}
		

	}
}
