pipeline {
	agent any
	stages {
		stage('Build Application') {
			steps {
				sh '/usr/local/apache-maven/bin/mvn -f java-tomcat-sample/pom.xml clean package'	
			}
			
			post {
				success {
					echo "Now , Perform Artifact"
					archiveArtifacts artifacts: '**/*.war'	
					}
			}
		}
		
		stage('Deploy Application to Staging Environment') {
			steps {
				buildjob : 'Deploy_Application_Staging_Env'	
			}
			
		}
		

	}
}
